apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: customer-churn-api
  labels:
    app: customer-churn-api
    release: monitoring

spec:
  selector:
    matchLabels:
      app: customer-churn-api

  namespaceSelector:
    matchNames:
      - kubeflow-user-example-com

  endpoints:
    - port: http
      path: /metrics
      interval: 15s
