apiVersion: v1
kind: ServiceAccount
metadata:
  name: customer-churn-sa
  namespace: customer-churn
  annotations:
    serving.kserve.io/s3-endpoint: "minio.ml-registry.svc.cluster.local:9000"
    serving.kserve.io/s3-usehttps: "0"
    serving.kserve.io/s3-region: "us-east-1"
    serving.kserve.io/s3-useanoncredential: "false"
    serving.kserve.io/s3-usevirtualbucket: "false"
secrets:
  - name: mlflow-minio-credentials
